## 1. Import reporting libraries and verify upstream evidence

In [1]:
import sys
from pathlib import Path
import hashlib
import json

import matplotlib.pyplot as plt
import numpy as np
import pandas as pd

sys.path.insert(0, "..")
from common_metrics import require, schedule_metrics

DATA_DIR = Path("output")


def sha256_file(path):
    return hashlib.sha256(Path(path).read_bytes()).hexdigest()

from validation import verify_stage, validate_schedule
for upstream in range(5):
    verify_stage(upstream)

## 2. Load project evidence

In [2]:
def first_existing(paths):
    for path in paths:
        if Path(path).is_file():
            return Path(path)
    return None


paths = {
    "canonical": first_existing([DATA_DIR / "canonical_schedule.csv"]),
    "specification": first_existing([DATA_DIR / "model_specification.json"]),
    "optimized": first_existing([DATA_DIR / "optimized_schedule_fairness_aware.csv"]),
    "scenario_summary": first_existing([DATA_DIR / "optimization_scenario_summary.csv"]),
    "robustness": first_existing([DATA_DIR / "robustness_evidence.json"]),
}
missing = [k for k, v in paths.items() if v is None]
require(not missing, f"Missing required project evidence: {missing}. Run notebooks 00-04 first.")



source_hashes = {k: sha256_file(v) for k, v in paths.items()}
model_specification = json.loads(paths["specification"].read_text(encoding="utf-8"))
robustness_evidence = json.loads(paths["robustness"].read_text(encoding="utf-8"))
historical = pd.read_csv(paths["canonical"])
optimized = pd.read_csv(paths["optimized"])
scenario_summary = pd.read_csv(paths["scenario_summary"])

for frame in [historical, optimized]:
    frame["week_start"] = pd.to_datetime(frame["week_start"], errors="raise")
    frame["week_end"] = pd.to_datetime(frame["week_end"], errors="raise")
    for column in ["nT", "rotation_group", "rotation_round"]:
        frame[column] = pd.to_numeric(frame[column], errors="raise").astype(int)

parameters = model_specification["parameters"]
derived_maps = model_specification["derived_maps"]
weekly_staffing_floor = int(parameters["weekly_staffing_floor"])
weekly_h24_required = int(parameters["weekly_h24_required"])
maximum_annual_workload = int(parameters["maximum_annual_workload"])
horizon_weeks = int(parameters["horizon_weeks"])
rotation_groups = [int(g) for g in parameters["rotation_groups"]]
group_sizes = {int(g): int(s) for g, s in derived_maps["group_sizes"].items()}
parameter_status = model_specification["parameter_status"]
structural_analysis = model_specification["structural_analysis"]

print("Loaded evidence chain from notebooks 00-04.")
print("Historical / optimized assignments:", len(historical), len(optimized))

Loaded evidence chain from notebooks 00-04.
Historical / optimized assignments: 931 923

## 3. Internal consistency check

In [3]:
pharmacies = sorted(derived_maps["primary_group_by_pharmacy"])
require(source_hashes["canonical"] == model_specification["canonical_sha256"], "Canonical lineage mismatch.")
for key, evidence_key in [("canonical","canonical_sha256"),("specification","model_specification_sha256"),("optimized","optimized_schedule_sha256")]:
    require(source_hashes[key] == robustness_evidence[evidence_key], f"Robustness {key} lineage mismatch.")
require(json.loads((DATA_DIR / "applied_model_specification.json").read_text()) == model_specification, "Applied specification mismatch.")
validate_schedule(optimized, historical, model_specification)
historical_metrics = schedule_metrics(historical,historical[["week_id","nT"]].drop_duplicates(),pharmacies)
optimized_metrics = schedule_metrics(optimized,optimized[["week_id","nT"]].drop_duplicates(),pharmacies)
selected_scenario_name = "Fairness-aware"
metric_columns = {"assignments":"assignments","total_min":"total_minimum","total_max":"total_maximum",
                  "total_range":"total_range","total_jain":"total_jain_index","total_gini":"total_gini",
                  "h24_min":"h24_minimum","h24_max":"h24_maximum","h24_range":"h24_range",
                  "h24_jain":"h24_jain_index","h24_gini":"h24_gini"}
scenario_files = {"Historical":paths["canonical"],"Efficiency-first":DATA_DIR/"optimized_schedule_efficiency_first.csv",
                  "Fairness-aware":paths["optimized"],"Full-group":DATA_DIR/"optimized_schedule_full_group.csv"}
require(set(scenario_summary.scenario) == set(scenario_files) and scenario_summary.scenario.is_unique, "Scenario names mismatch.")
for name, path in scenario_files.items():
    frame=pd.read_csv(path)
    if name != "Historical":validate_schedule(frame,historical,model_specification)
    metrics=schedule_metrics(frame,frame[["week_id","nT"]].drop_duplicates(),pharmacies)
    row=scenario_summary.set_index("scenario").loc[name]
    for column,key in metric_columns.items():
        require(np.isclose(row[column],metrics[key],rtol=1e-10,atol=1e-12),f"Scenario {name}: {column} mismatch.")
    require(row.reduction_vs_history == len(historical)-len(frame), "Assignment reduction mismatch.")
consistency_checks = pd.DataFrame([
    ("All scenario metrics match materialized schedules",True,"4 scenarios; all exported metrics"),
    ("Weekly staffing floor satisfied",True,f"minimum weekly active = {optimized.groupby('week_id').size().min()}"),
    ("All modeled schedule constraints",True,"metadata, unique assignments, eligibility, staffing, H24, cycle bounds, workload, repeated patterns"),
    ("Evidence lineage",True,"stage manifests and cross-artifact hashes checked"),
],columns=["check","passed","evidence"])
consistency_checks["status"]="PASS"
display(consistency_checks[["check","status","evidence"]])

                                               check  ...                                           evidence
0  All scenario metrics match materialized schedules  ...                  4 scenarios; all exported metrics
1                    Weekly staffing floor satisfied  ...                         minimum weekly active = 17
2                   All modeled schedule constraints  ...  metadata, unique assignments, eligibility, sta...
3                                   Evidence lineage  ...  stage manifests and cross-artifact hashes checked

[4 rows x 3 columns]

## 4. Explain pattern and pharmacy changes

In [4]:

nt_values=sorted(historical.nT.unique())
change_rows=[]
for nt in nt_values:
    a=historical[historical.nT==nt];b=optimized[optimized.nT==nt]
    active_a,active_b=set(a.pharmacy_id),set(b.pharmacy_id)
    h24_a=set(a.loc[a.shift_type.eq("H24"),"pharmacy_id"])
    h24_b=set(b.loc[b.shift_type.eq("H24"),"pharmacy_id"])
    cols=["pharmacy_id","location_id","shift_type","access_mode"]
    changed=set(a[cols].itertuples(index=False,name=None)) != set(b[cols].itertuples(index=False,name=None))
    if changed:
        change_rows.append({"nT":int(nt),"historical_count":len(active_a),"optimized_count":len(active_b),
            "active_set_changed":active_a!=active_b,"h24_set_changed":h24_a!=h24_b,
            "added":json.dumps(sorted(active_b-active_a)),"removed":json.dumps(sorted(active_a-active_b)),
            "h24_added":json.dumps(sorted(h24_b-h24_a)),"h24_removed":json.dumps(sorted(h24_a-h24_b))})
changed_nt=pd.DataFrame(change_rows,columns=["nT","historical_count","optimized_count","active_set_changed","h24_set_changed","added","removed","h24_added","h24_removed"])
display(changed_nt)
print(f"Changed full patterns: {len(changed_nt)} / {len(nt_values)}; active sets: {changed_nt.active_set_changed.sum()}; H24 sets: {changed_nt.h24_set_changed.sum()}")

Changed full patterns: 11 / 42; active sets: 9; H24 sets: 3

    nT  historical_count  optimized_count  ...    removed  h24_added h24_removed
0    9                18               17  ...  ["P0021"]         []          []
1   10                18               17  ...  ["P0049"]         []          []
2   16                18               17  ...  ["P0020"]         []          []
3   17                18               17  ...  ["P0045"]         []          []
4   21                17               17  ...  ["P0076"]  ["P0111"]   ["P0076"]
5   22                17               17  ...         []  ["P0009"]   ["P0003"]
6   23                18               17  ...  ["P0029"]         []          []
7   24                18               17  ...  ["P0039"]         []          []
8   25                17               17  ...         []  ["P0057"]   ["P0067"]
9   30                18               17  ...  ["P0034"]         []          []
10  31                18               17  ...  ["P0037"]         []          []

[11 rows x 9 columns]

## 5. Compare scenarios and select the recommendation

In [5]:
comparison_columns = ["assignments", "total_range", "h24_range"]


def is_dominated(row, frame):
    '''A scenario is Pareto-dominated if some other scenario is at least as good on every
    metric and strictly better on at least one.'''
    others = frame.drop(index=row.name)
    weakly_better = others[comparison_columns].le(row[comparison_columns].to_numpy()).all(axis=1)
    strictly_better = others[comparison_columns].lt(row[comparison_columns].to_numpy()).any(axis=1)
    return bool((weakly_better & strictly_better).any())


scenario_comparison = scenario_summary.copy()
scenario_comparison["pareto_efficient"] = ~scenario_comparison.apply(lambda r: is_dominated(r, scenario_comparison), axis=1)
scenario_comparison = scenario_comparison.sort_values(
    model_specification["recommendation_order"] + ["scenario"]
).reset_index(drop=True)
recommended_scenario = str(scenario_comparison.iloc[0]["scenario"])
require(recommended_scenario == selected_scenario_name, "Exported schedule does not match the documented decision rule.")
scenario_comparison["recommended"] = scenario_comparison["scenario"].eq(recommended_scenario)
display(scenario_comparison[["scenario", "assignments", "total_range", "h24_range", "pareto_efficient", "recommended"]])

           scenario  assignments  ...  pareto_efficient  recommended
0    Fairness-aware          923  ...              True         True
1        Full-group          931  ...             False        False
2        Historical          931  ...             False        False
3  Efficiency-first          901  ...              True        False

[4 rows x 6 columns]

## 6. Final validation, robustness interpretation, and report

In [6]:
robustness_results=robustness_evidence["results"]
robustness_group_summary=pd.DataFrame(robustness_evidence["group_summary"])
plan=pd.read_csv(DATA_DIR/"single_absence_response_plan.csv",keep_default_na=False)
scheduled=plan[plan.was_scheduled_active]
require(len(plan)==robustness_results["tested_pattern_absences"],"Response count mismatch.")
require(len(scheduled)==robustness_results["scheduled_active_absences"],"Scheduled count mismatch.")
require(int(scheduled.hard_constraints_recoverable_within_group.sum())==robustness_results["recoverable_within_group"],"Recovery count mismatch.")
require(int(scheduled.cross_group_authorization_required.sum())==robustness_results["total_requiring_human_intervention"],"Manual count mismatch.")
require(int(scheduled.secondary_eligible_candidate_from_history.ne("").sum())==robustness_results["historical_candidates_requiring_approval"],"Candidate count mismatch.")
require(len(pd.read_csv(DATA_DIR/"authorized_substitutions_template.csv"))==robustness_results["total_requiring_human_intervention"],"Authorization template omits events.")
final_validation_checklist=pd.DataFrame([
    ("Data and implementation lineage","Stage manifests and explicit canonical/specification/optimized/robustness links verified","PASS"),
    ("All scenario schedules","All exported schedule constraints and summary metrics checked","PASS"),
    ("Pattern-level recovery","Every reported same-group success and historical candidate materialized and checked","PASS"),
    ("Cross-group boundary",f"{robustness_results['total_requiring_human_intervention']} simulated cases need a cross-group decision; no approval records are invented","DOCUMENTED MODEL OUTCOME"),
    ("Group bound",structural_analysis["conclusion"],"PROVEN UNDER STATED ASSUMPTIONS"),
    ("Staffing and workload thresholds","Derived from source minima/maxima and retained by explicit continuity policy","JUSTIFIED MODEL CHOICE"),
    ("Calendar boundary","Final block ends 2027-01-03, six elapsed days after Monday start; source preserved and limitation documented","CAVEAT"),
    ("Dataset-only scope","No geography, actual availability, demand, preferences or external rules added; excluded by project scope","SCOPE SATISFIED"),
    ("Recovery scope","Pattern-level, one absence at a time; H24 moves may affect other patterns, total fairness is not locked","CAVEAT"),
],columns=["project_component","evidence","status"])
display(final_validation_checklist)
from reporting import build_report
final_report=build_report(historical_metrics,optimized_metrics,scenario_comparison,changed_nt,
                         robustness_evidence,model_specification,
                         json.loads((DATA_DIR/"observed_data_profile.json").read_text()),
                         final_validation_checklist)
print(final_report)

# Fair and Constraint-Aware Pharmacy Shift Scheduling

## Abstract

This project investigates pharmacy duty scheduling as a constrained allocation of workload. The sole empirical input is the supplied TURNI CSV. The Bologna city-area calendar contains 53 weekly blocks, 123 rotating pharmacies and 931 assignments, organized into 42 recurring patterns and seven dominant rotation groups. A mixed-integer linear program preserves a historical staffing floor, H24 duty count, primary-group eligibility, a horizon workload ceiling and a policy of balanced H24 cycle counts. It compares efficiency-first, fairness-aware and full-group scenarios using lexicographic priorities.

The selected fairness-aware schedule has 923 assignments, total workload range 1 and H24 range 1, compared with 931, 2 and 3 historically. Total Jain improves slightly, but total Gini increases slightly; fairness improvement is metric-specific. 11 complete nT patterns change, including 2 with H24-only changes.

The robustness experiment tests 738 eligible pharmacy-pattern cases, of which 730 affect scheduled pharmacies. 424 (58.1%) have a materialized, model-feasible same-group response. All 306 remaining cases (41.9%) require human intervention. 17 have a historically evidenced candidate; these are not automatically authorized. These are completed results of a dataset-only computational case study; unrecorded real-world variables are excluded by design.

## 1. Research question and ethical framing

The research question is: how can the observed rotation be retained while reducing selected workload disparities, testing single-pharmacy pattern unavailability and explaining the resulting decisions?

### Dataset-only scope and completion criterion

The project uses only the CSV supplied in the original archive as empirical input. No geographic, actual-availability, demand, preference or external legal/contractual dataset is added. Those subjects are outside the agreed project scope and are not unfinished submission requirements. The analysis is complete when the reconstructed data, explicitly justified model, optimized schedules, simulated robustness results and report agree and can be reproduced from that input.

The distinction between observation and modeling is maintained throughout. Counts, dates, identifiers, H24/STANDARD labels, P/C labels and historical co-occurrences are observations or deterministic derivations. Workload equality, scenario priorities, historical continuity and the choice to simulate one absence at a time are analytical design choices. They are justified explicitly rather than attributed to information absent from the file. References support mathematical methods and the ethics discussion; they provide no additional pharmacy data.

Duty scheduling affects pharmacy organizations, workers, citizens and scheduling authorities. Fewer assignments can reduce measured workload but also remove redundancy, income opportunities or service availability. Equal pharmacy counts do not establish equal public access. The model's preferred outcome therefore depends on the objective chosen by the scheduling authority.

The European Commission's Trustworthy AI guidelines identify human oversight, technical robustness, privacy and data governance, transparency, fairness and accountability among their requirements. These provide an ethical framing for this case study; passing the computational checks is not certification against those guidelines. [1]

No protected-attribute, ownership, workforce, revenue or preference data are included. The project measures count-based allocation fairness among modeled pharmacies. It does not establish demographic parity, equal opportunity, legal compliance or absence of discrimination. Pseudonymizing names also does not remove inequities potentially embedded in historical group membership.

## 2. Dataset, reconstruction and privacy

The supplied CSV is a semi-structured spreadsheet export with date blocks, shift-section headers and pharmacy assignment rows. Notebook 00 checks the expected column layout, normalizes Unicode and whitespace, accepts assignment rows with access mode P or C and excludes two rows explicitly marked as outside the duty rotation. Names and addresses are replaced by pharmacy and location identifiers; source-row positions are retained for traceability.

The source distinguishes H24 from STANDARD service, and P (open-door) from C (call/closed-door) access. The source headers describe H24 as Monday 08:30 to the following Monday 08:30, and STANDARD duty as 08:30-12:30 and 15:30-19:30, Monday through Sunday. These labels describe the source; the model counts weekly assignments rather than simulating actual opening hours. One assignment is a pharmacy-week duty block, not an employee shift, working-hour total or full-time-equivalent measure.

| Property | Value |
| --- | --- |
| Weekly blocks | 53 |
| Distinct nT patterns | 42 |
| Rotating pharmacies | 123 |
| Historical assignment rows | 931 |
| Historical H24 assignments | 159 |
| Historical STANDARD assignments | 772 |
| Weekly historical staffing | 17-18 |
| H24 pharmacies in each block | 3 |
| Maximum assignments per pharmacy in the horizon | 8 |
| Excluded non-rotation facilities | 2 |
| Group sizes, in group order | 17, 18, 18, 17, 18, 18, 17 |

The first block begins on 29 December 2025 and ends on 5 January 2026. The final block begins on 28 December 2026 and is recorded as ending on 3 January 2027. That final end date is Sunday, six elapsed days after Monday start, inconsistent with a uniform Monday-to-Monday handover. Counting seven inclusive calendar dates does not resolve that timing inconsistency. The pipeline preserves the original boundary and records it as a source-data limitation; it does not guess a corrected date or require a second dataset to complete the analysis. Throughout this report, horizon workload means counts over all 53 source blocks, including the boundary anomaly, rather than hours or a strict 365-day total.

Sequential pseudonyms are not anonymization. Source-row positions, rare schedule features and the public calendar can enable linkage. The raw CSV and private mapping files contain the identifying information supplied with the project and are retained for reproducibility. They are excluded by the supplied version-control ignore rules. Analytical outputs use pseudonyms, but are not claimed to be irreversibly anonymous. Existing mappings are validated and new IDs start above the largest existing identifier, preventing collisions when a later dataset adds pharmacies or locations.

### Access modes, locations and source fidelity

The reconstructed calendar has 124 distinct pharmacy-location identifiers for 123 pharmacies. 118 pharmacies have mode P and 5 have mode C; no pharmacy changes P/C label across its observed rows. One pharmacy has two observed locations. Locations are retained as identifiers and are not converted into a geographic coverage model. Every accepted row preserves its source-row reference, and all accepted rows occur exactly once in the canonical output.

## 3. Computational pipeline and rotation evidence

The six notebooks execute in order: cleaning and canonicalization; descriptive baseline; constraint specification; MILP optimization; pattern-level robustness; final comparison and reporting. They exchange explicit CSV and JSON artifacts rather than relying on notebook memory. All three optimized schedules are exported, allowing every scenario's reported metrics to be checked against its actual rows.

The canonicalizer reconstructs dates, nT labels, groups, rounds, shift types and access modes. It verifies row counts, unique pharmacy-week assignments, consecutive weekly starts, adjacent boundaries, nT progression and consistent week metadata. The baseline checks repeated patterns and the constant H24 count. Identical nT values reuse the same pharmacy, location, shift and access signature across their calendar occurrences; there are 11 matching repeated-pattern comparisons out of 11.

For candidate periods 2 through 41, membership purity is the sum, across pharmacies, of the largest assignment count in any nT residue class, divided by all assignment rows. The leading period is 7 with purity 0.998926. One historical cross-group row means purity is not perfect. Dominant historical membership determines each pharmacy's primary modeled group; this is an inference from observations, not an externally supplied authorization list.

The revised permutation sensitivity test randomizes the 42 nT labels as intact pattern blocks, preserving each pattern's pharmacy membership and repeated-week multiplicity. Each randomization repeats the entire candidate-period search. It uses B=500 permutations and finds b=0 null maxima at least as extreme as the observed maximum. The corrected Monte Carlo p-value is (b+1)/(B+1) = 0.001996. Randomly sampled permutation p-values should not be reported as zero. [2]

This result supports the period under an exchangeable-pattern-label null. It is exploratory evidence, not proof of an administrative rule or stability in another year. The original row-level label shuffle disrupted within-pattern structure and repeated blocks; the revised procedure retains those dependencies. The significance claim is limited to this explicit randomization null.

Each stage records hashes of relevant inputs, outputs and implementation modules; downstream stages check those manifests before use. Notebook 05 additionally checks the explicit canonical, applied-specification, optimized-schedule and robustness links. Hashes detect accidental stale or altered artifacts relative to recorded manifests; they are not authentication, external validation or proof that a formula is correct.

### Numerical settings for the exploratory test

Candidate periods are 2 through 41, inclusive. The random seed is 0. The mean of the null best-purity values is 0.665429, and their maximum is 0.794844. The number of permutations controls Monte Carlo resolution; it is a computational precision setting, not a pharmacy-data value or a fairness threshold. A 0.01 significance cutoff is an explicit screening choice used to stop the pipeline if this exploratory structural evidence is weak, rather than a requirement inferred from pharmacy data. The complete search is repeated for each draw, so the null comparison accounts for selection of the leading candidate.

## 4. Fairness definition and parameter provenance

For N nonnegative pharmacy workloads w_i, range is max(w_i)-min(w_i), and population variance is the mean squared deviation from the mean workload. Range is understandable and easy to model linearly, but ignores changes between the extremes.

Jain's index is J(w) = (sum w_i)^2 / (N * sum w_i^2). For a nonzero nonnegative allocation its range is 1/N to 1, with 1 representing equality. [3] The project computes it descriptively; it is not a MILP objective. Gini is G(w) = sum over i,j of |w_i-w_j| / (2*N*sum w_i). Higher Gini indicates more inequality. Both metrics are evaluated across all 123 pharmacies, including any zero H24 counts. The code's all-zero convention is Jain=1 and Gini undefined; no reported schedule has zero aggregate workload. For a finite nonnegative N-pharmacy allocation, the maximum uncorrected Gini is (N-1)/N; no finite-sample correction is applied.

| Parameter or choice | Value / policy | Evidence status |
| --- | --- | --- |
| Weekly staffing floor | 17 | Historical minimum used as an unvalidated proxy |
| Horizon workload ceiling | 8 | Historical maximum used as an unvalidated proxy |
| Weekly H24 count | Exactly 3 | Observed constant retained by modeling policy |
| Primary-group eligibility | Dominant historical group | Observed association converted into an eligibility assumption |
| Shared nT decisions | All occurrences identical | Observed recurrence retained as policy |
| H24 cycle counts per pharmacy | 1-2 in 17-member groups; exactly 1 in 18-member groups | Normative equal-count allocation derived from 18 cycle slots |
| Recommended objective | Total range, H24 range, assignment count | Normative priority |
| Historical changes | Lower-priority tie-breakers | Normative continuity preference |

The cycle bounds deserve particular emphasis: six patterns per group times three H24 duties gives 18 H24 slots. Allocating those as evenly as possible yields floor(18/group size) and ceiling(18/group size). This is a hard equal-count fairness policy. Arithmetic derives its values, but does not make the policy an observed fact. Because the CSV has no capability variable, service type is modeled as reassignable among the primary-group members. This is an explicit symmetry assumption used for count-based optimization, not an additional capability observation.

Counts also omit differences in holidays, call duty, demand, staff size, costs, income and actual duration. A burden-adjusted objective would need weights unsupported by this dataset. Accordingly, no such weights are invented; total and H24 counts are analyzed separately.

## 5. Mathematical model

Let I be the pharmacy set, T the 42 patterns, g(t) the structural group of a pattern, g_i the dominant group of pharmacy i, and m_t the number of calendar occurrences of pattern t. Eligible decisions are E = {(i,t): g_i=g(t)}. For each eligible pair, binary y_it indicates active duty and binary h_it indicates H24 duty. Noneligible pairs are absent from the variable set.

Define total workload W_i = sum_t m_t*y_it and H24 workload H_i = sum_t m_t*h_it. H24 cycle workload C_i = sum_t h_it counts distinct patterns, with no occurrence weight. The implemented hard constraints are:

1. For every pattern t, sum_i y_it >= 17.
2. For every pattern t, sum_i h_it = 3.
3. For every eligible pair, h_it <= y_it.
4. For every pharmacy i, W_i <= 8 over the 53-block horizon.
5. For every pharmacy i in group g, floor(18/size_g) <= C_i <= ceiling(18/size_g).
6. Auxiliary extrema satisfy W_min <= W_i <= W_max and H_min <= H_i <= H_max; their differences define the two range objectives.

The variables y and h are binary. The four auxiliary extrema are continuous and bounded between zero and the horizon ceiling. Pattern-level variables enforce identical repeated nT assignments by construction. Location and access mode are carried from observed pharmacy metadata and checked in the materialized rows; neither is optimized.

The mixed-integer problem is solved through SciPy's milp interface to HiGHS. Each lexicographic stage must terminate successfully at zero reported relative MIP gap; bounds, integrality and linear-constraint residuals are checked before the objective is locked. Solver objectives and dual bounds are exported in solver_evidence.json. SciPy documents the MILP status and gap fields used for these checks. [4]

The scenario priority orders are:

- Efficiency-first: assignments, total range, H24 range, active changes, H24 changes.
- Fairness-aware: total range, H24 range, assignments, active changes, H24 changes.
- Full-group: fix every eligible y_it to one, then minimize H24 range and H24 changes.

Changes are weighted by calendar occurrences. Their linear coefficient is m_t minus twice the number of historical occurrences of that decision; a constant can be omitted without changing the minimizing solution. The unavoidable removal of an ineligible historical cross-group row is another constant. These tie-breakers minimize changed active/H24 decisions, not the number of distinct changed patterns. Equal objective values can therefore allow different detailed schedules across solver versions.

The historical schedule is a descriptive comparator. It contains a cross-group exception and need not satisfy the revised eligibility and cycle-balance policy; it is not presented as a feasible point of the same model.

## 6. Fairness and efficiency results

| Scenario | Assignments | Total range | H24 range | Nondominated* | Selected |
| --- | --- | --- | --- | --- | --- |
| Fairness-aware | 923 | 1 | 1 | True | True |
| Full-group | 931 | 1 | 1 | False | False |
| Historical | 931 | 2 | 3 | False | False |
| Efficiency-first | 901 | 3 | 1 | True | False |

*The table's nondominance labels compare the four displayed candidates over assignments, total range and H24 range. They do not enumerate the full feasible frontier. For the lexicographically optimized scenarios, optimality is separately supported by the solver evidence. Dominance uses only the declared comparison metrics and is not a claim about every ethical consideration.

The fairness-aware schedule removes 8 assignments (0.86% of history) and uses 22 more assignments than efficiency-first. It narrows total workload from 6-8 to 7-8 assignments and H24 workload from 0-3 to 1-2 assignments per pharmacy. Full-group matches those ranges but uses eight more assignments. It is dominated under the selected three metrics, yet has better total Jain and Gini than fairness-aware. Thus the preferred scenario depends on the specific fairness objective, not on a universal ordering of fairness.

| Measure | Historical | Fairness-aware |
| --- | --- | --- |
| Assignments | 931 | 923 |
| Total workload range | 2 | 1 |
| H24 workload range | 3 | 1 |
| Total Jain | 0.995456618 | 0.995580284 |
| Total Gini | 0.033306262 | 0.033313074 |
| Total population variance | 0.261484566 | 0.249983475 |
| H24 Jain | 0.867242976 | 0.889768768 |
| H24 Gini | 0.176100629 | 0.160147262 |

Total Jain increases slightly. Total Gini increases from 0.033306262 to 0.033313074, a small worsening of 0.000006812; both round to 0.0333 at four decimals. It would be incorrect to say that all fairness indices improve. The strongest positive results are the reduced total and H24 ranges and the improved H24 distribution.

There are 11 changed full patterns and 31 unchanged patterns in this executed solution. 9 patterns change active membership and 3 change H24 membership; 2 have H24-only changes. nt_change_explanation.csv records both types, including added and removed H24 IDs. A count based only on active pharmacies misses the H24-only changes. Patterns should not be called overstaffed merely because they exceed the historical-minimum proxy.

### All scenario fairness statistics

| Scenario | Total min | Total max | H24 min | H24 max | Total Jain | Total Gini | H24 Jain | H24 Gini |
| --- | --- | --- | --- | --- | --- | --- | --- | --- |
| Historical | 6 | 8 | 0 | 3 | 0.995457 | 0.033306 | 0.867243 | 0.176101 |
| Efficiency-first | 5 | 8 | 1 | 2 | 0.988469 | 0.054050 | 0.889769 | 0.160147 |
| Fairness-aware | 7 | 8 | 1 | 2 | 0.995580 | 0.033313 | 0.889769 | 0.160147 |
| Full-group | 7 | 8 | 1 | 2 | 0.995738 | 0.032398 | 0.889769 | 0.160147 |

### Workload distributions

| Schedule | Workload type | Assignments per pharmacy | Pharmacies |
| --- | --- | --- | --- |
| Historical | Total | 6 | 1 |
| Historical | Total | 7 | 51 |
| Historical | Total | 8 | 71 |
| Historical | H24 | 0 | 1 |
| Historical | H24 | 1 | 87 |
| Historical | H24 | 2 | 33 |
| Historical | H24 | 3 | 2 |
| Fairness-aware | Total | 7 | 61 |
| Fairness-aware | Total | 8 | 62 |
| Fairness-aware | H24 | 1 | 87 |
| Fairness-aware | H24 | 2 | 36 |

These distributions make the range and inequality calculations auditable from counts of pharmacies rather than only aggregate indices. All N pharmacies enter each distribution; zeros are included for historical H24.

### Changes measured at calendar level

| Scenario | Active decision changes | H24 decision changes |
| --- | --- | --- |
| Historical | 0 | 0 |
| Efficiency-first | 32 | 6 |
| Fairness-aware | 10 | 6 |
| Full-group | 2 | 6 |

A changed active or H24 decision means an added or removed pharmacy-week binary decision. Replacing one pharmacy with another counts as two changes, and recurring nT patterns contribute once for each affected calendar occurrence. These counts therefore differ from the number of distinct changed patterns.


                  project_component  ...                           status
0   Data and implementation lineage  ...                             PASS
1            All scenario schedules  ...                             PASS
2            Pattern-level recovery  ...                             PASS
3              Cross-group boundary  ...         DOCUMENTED MODEL OUTCOME
4                       Group bound  ...  PROVEN UNDER STATED ASSUMPTIONS
5  Staffing and workload thresholds  ...           JUSTIFIED MODEL CHOICE
6                 Calendar boundary  ...                           CAVEAT
7                Dataset-only scope  ...                  SCOPE SATISFIED
8                    Recovery scope  ...                           CAVEAT

[9 rows x 3 columns]

## 7. Export the final project artifacts

In [7]:


(DATA_DIR / "final_project_report.md").write_text(final_report, encoding="utf-8")
changed_nt.to_csv(DATA_DIR / "nt_change_explanation.csv", index=False)
scenario_comparison.to_csv(DATA_DIR / "scenario_pareto_comparison.csv", index=False)
final_validation_checklist.to_csv(DATA_DIR / "final_validation_checklist.csv", index=False)

final_project_evidence = {
    "evidence_type": "final_project_comparison",
    "source_hashes": source_hashes,
    "recommended_scenario": recommended_scenario,
    "historical_metrics": historical_metrics,
    "optimized_metrics": optimized_metrics,
    "robustness_results": robustness_results,
    "structural_analysis": structural_analysis,
    "geography_used": False,
}
Path(DATA_DIR / "final_project_evidence.json").write_text(
    json.dumps(final_project_evidence, ensure_ascii=False, indent=2), encoding="utf-8"
)
print("Saved: output/final_project_report.md and supporting CSV/JSON evidence files.")

from validation import write_stage
write_stage(5, ['output/stage_00_manifest.json', 'output/stage_01_manifest.json', 'output/stage_02_manifest.json', 'output/stage_03_manifest.json', 'output/stage_04_manifest.json'], ['output/final_project_report.md', 'output/nt_change_explanation.csv', 'output/scenario_pareto_comparison.csv', 'output/final_validation_checklist.csv', 'output/final_project_evidence.json'])

Saved: output/final_project_report.md and supporting CSV/JSON evidence files.